before_script: "psql -c 'create database rapns_test;' -U postgres >/dev/null"
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-19mode